# Generated by Django 3.2.5 on 2021-07-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name_urdu', models.CharField(max_length=200)),
                ('book_name_english', models.CharField(max_length=200)),
                ('book_detail_English', models.TextField(max_length=200)),
                ('book_detail_urdu', models.TextField(max_length=200)),
                ('book_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_english', models.CharField(max_length=100)),
                ('title_urdu', models.CharField(max_length=100)),
                ('detail_urdu', models.TextField()),
                ('detail_english', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='events/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_english', models.CharField(max_length=100)),
                ('title_urdu', models.CharField(max_length=100)),
                ('detail_urdu', models.TextField()),
                ('detail_english', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_english', models.CharField(max_length=100)),
                ('title_urdu', models.CharField(max_length=100)),
                ('detail_urdu', models.TextField()),
                ('detail_english', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
